/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddJobResult = { 'ok' : bigint } |
  { 'err' : string };
export type AddServiceResult = { 'ok' : bigint } |
  { 'err' : string };
export interface AdminJob {
  'id' : bigint,
  'title' : string,
  'salary' : string,
  'notifDate' : string,
  'vacancy' : string,
  'fees' : string,
  'createdAt' : bigint,
  'lastDate' : string,
}
export interface AdminService {
  'id' : bigint,
  'subServices' : Array<SubServiceItem>,
  'mainNameEn' : string,
  'mainNameMr' : string,
}
export interface Appointment {
  'id' : bigint,
  'customerName' : string,
  'createdAt' : bigint,
  'mobileNumber' : string,
  'preferredTime' : [] | [string],
}
export interface ShivSevaKendra {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface SubServiceItem { 'nameEn' : string, 'nameMr' : string }
export interface _SERVICE {
  'addJob' : ActorMethod<
    [string, string, string, string, string, string],
    AddJobResult
  >,
  'addService' : ActorMethod<
    [string, string, Array<SubServiceItem>],
    AddServiceResult
  >,
  'bookAppointment' : ActorMethod<[string, string, [] | [string]], bigint>,
  'deleteJob' : ActorMethod<[bigint], boolean>,
  'deleteService' : ActorMethod<[bigint], boolean>,
  'getAdminJobs' : ActorMethod<[], Array<AdminJob>>,
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getAdminServices' : ActorMethod<[], Array<AdminService>>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getShivSevaKendraInfo' : ActorMethod<[], ShivSevaKendra>,
  'setAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];