/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AddJobResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const SubServiceItem = IDL.Record({
  'nameEn' : IDL.Text,
  'nameMr' : IDL.Text,
});
export const AddServiceResult = IDL.Variant({
  'ok' : IDL.Nat,
  'err' : IDL.Text,
});
export const AdminJob = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'salary' : IDL.Text,
  'notifDate' : IDL.Text,
  'vacancy' : IDL.Text,
  'fees' : IDL.Text,
  'createdAt' : IDL.Int,
  'lastDate' : IDL.Text,
});
export const AdminService = IDL.Record({
  'id' : IDL.Nat,
  'subServices' : IDL.Vec(SubServiceItem),
  'mainNameEn' : IDL.Text,
  'mainNameMr' : IDL.Text,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdAt' : IDL.Int,
  'mobileNumber' : IDL.Text,
  'preferredTime' : IDL.Opt(IDL.Text),
});
export const ShivSevaKendra = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addJob' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [AddJobResult],
      [],
    ),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(SubServiceItem)],
      [AddServiceResult],
      [],
    ),
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deleteJob' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAdminJobs' : IDL.Func([], [IDL.Vec(AdminJob)], ['query']),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAdminServices' : IDL.Func([], [IDL.Vec(AdminService)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getShivSevaKendraInfo' : IDL.Func([], [ShivSevaKendra], ['query']),
  'setAdmin' : IDL.Func([], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AddJobResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const SubServiceItem = IDL.Record({
    'nameEn' : IDL.Text,
    'nameMr' : IDL.Text,
  });
  const AddServiceResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const AdminJob = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'salary' : IDL.Text,
    'notifDate' : IDL.Text,
    'vacancy' : IDL.Text,
    'fees' : IDL.Text,
    'createdAt' : IDL.Int,
    'lastDate' : IDL.Text,
  });
  const AdminService = IDL.Record({
    'id' : IDL.Nat,
    'subServices' : IDL.Vec(SubServiceItem),
    'mainNameEn' : IDL.Text,
    'mainNameMr' : IDL.Text,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdAt' : IDL.Int,
    'mobileNumber' : IDL.Text,
    'preferredTime' : IDL.Opt(IDL.Text),
  });
  const ShivSevaKendra = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [AddJobResult],
        [],
      ),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(SubServiceItem)],
        [AddServiceResult],
        [],
      ),
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deleteJob' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAdminJobs' : IDL.Func([], [IDL.Vec(AdminJob)], ['query']),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAdminServices' : IDL.Func([], [IDL.Vec(AdminService)], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getShivSevaKendraInfo' : IDL.Func([], [ShivSevaKendra], ['query']),
    'setAdmin' : IDL.Func([], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };