/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShivSevaKendra {
    name: string;
    email: string;
    address: string;
    phone: string;
}
export type AddJobResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface AdminJob {
    id: bigint;
    title: string;
    salary: string;
    notifDate: string;
    vacancy: string;
    fees: string;
    createdAt: bigint;
    lastDate: string;
}
export type AddServiceResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface SubServiceItem {
    nameEn: string;
    nameMr: string;
}
export interface Appointment {
    id: bigint;
    customerName: string;
    createdAt: bigint;
    mobileNumber: string;
    preferredTime?: string;
}
export interface AdminService {
    id: bigint;
    subServices: Array<SubServiceItem>;
    mainNameEn: string;
    mainNameMr: string;
}
export interface backendInterface {
    addJob(title: string, notifDate: string, vacancy: string, salary: string, lastDate: string, fees: string): Promise<AddJobResult>;
    addService(mainNameEn: string, mainNameMr: string, subServices: Array<SubServiceItem>): Promise<AddServiceResult>;
    bookAppointment(customerName: string, mobileNumber: string, preferredTime: string | null): Promise<bigint>;
    deleteJob(id: bigint): Promise<boolean>;
    deleteService(id: bigint): Promise<boolean>;
    getAdminJobs(): Promise<Array<AdminJob>>;
    getAdminPrincipal(): Promise<Principal | null>;
    getAdminServices(): Promise<Array<AdminService>>;
    getAppointments(): Promise<Array<Appointment>>;
    getShivSevaKendraInfo(): Promise<ShivSevaKendra>;
    setAdmin(): Promise<boolean>;
}
import type { AddJobResult as _AddJobResult, AddServiceResult as _AddServiceResult, Appointment as _Appointment } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addJob(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<AddJobResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_AddJobResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_AddJobResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addService(arg0: string, arg1: string, arg2: Array<SubServiceItem>): Promise<AddServiceResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(arg0, arg1, arg2);
                return from_candid_AddServiceResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(arg0, arg1, arg2);
            return from_candid_AddServiceResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async bookAppointment(arg0: string, arg1: string, arg2: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteJob(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteService(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteService(arg0);
            return result;
        }
    }
    async getAdminJobs(): Promise<Array<AdminJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminJobs();
            return result;
        }
    }
    async getAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminServices(): Promise<Array<AdminService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminServices();
            return result;
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShivSevaKendraInfo(): Promise<ShivSevaKendra> {
        if (this.processError) {
            try {
                const result = await this.actor.getShivSevaKendraInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShivSevaKendraInfo();
            return result;
        }
    }
    async setAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin();
            return result;
        }
    }
}
function from_candid_AddJobResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddJobResult): AddJobResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_AddServiceResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddServiceResult): AddServiceResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    createdAt: bigint;
    mobileNumber: string;
    preferredTime: [] | [string];
}): {
    id: bigint;
    customerName: string;
    createdAt: bigint;
    mobileNumber: string;
    preferredTime?: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        createdAt: value.createdAt,
        mobileNumber: value.mobileNumber,
        preferredTime: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.preferredTime))
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n7(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
